export const events = [
  { id: 1, title: 'Daily', location: 'Home', start: 60, end: 120 },
  { id: 2, title: 'Sprint summary', location: 'Office', start: 70, end: 130 },
  {
    id: 3,
    title: 'Coffee with Yakov',
    location: 'Ziona Cafe',
    start: 100,
    end: 150,
  },
  { id: 4, title: 'Football game', location: '', start: 140, end: 190 },
  {
    id: 5,
    title: 'Haircut',
    location: 'Aviv barbershop',
    start: 160,
    end: 210,
  },
  { id: 6, title: 'Interview', location: 'Zoom', start: 300, end: 360 },
  { id: 7, title: 'Lunch', location: 'Home', start: 310, end: 410 },
  {
    id: 8,
    title: 'Meeting with a Amit',
    location: "Amit's house",
    start: 390,
    end: 430,
  },
  {
    id: 9,
    title: 'Tennis with Omer',
    location: 'Tennis Court',
    start: 420,
    end: 500,
  },
];
